### ISSUE TITLE
Tests for SQL extraction backend

### ISSUE THREAD

**Issue by carsonharmon** [trailofbits/tourniquet#6]
Write tests to confirm that the proper tables are made and that the proper info is in the tables

**Comment by aaron-suarez** [comment]
I was trying to write a unit test for the methods that create tables and line maps and such, and I ran into an issue where I was trying to mock the database connection and I encountered this
```
E       TypeError: can't set attributes of built-in/extension type 'sqlite3.Cursor'
```

In doing some further research into the issue, I realize that we won't be able to mock the database connection and therefore we'll want to create a wrapper class for the DB rather than using the connection directly in our class. Then we can mock our wrapper class for the unit tests.

After I had this epiphany, I realized you've already thought of this with this TODO comment:

https://github.com/trailofbits/tourniquet/blob/57396bee41c9b63aa1500c8693fff0e380413f7d/tourniquet/tourniquet.py#L14

That being said, would you like me to open a proper issue for creating this class for a DB wrapper? Then once we knock that out, we can write the tests to fix this issue.

**Comment by woodruffw** [comment]
I _think_ we're actually going to remove most of this code -- my plan is to refactor tourniquet to use SQLAlchemy instead of raw connections and queries. SQLAlchemy should take care of the appropriate table construction for us; new unit tests will just be a matter of using the appropriate connection fixtures. But thanks for volunteering here!

**Comment by aaron-suarez** [comment]
I also prefer SQLAlchemy, so that's a really good idea. Instead of writing tests for code that's going away, I'll contact you on slack to talk about how else I can help out

**Comment by woodruffw** [comment]
Superseded by #23.
